# Generated by Django 4.2.1 on 2023-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='bilan',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='bilan',
            old_name='amount',
            new_name='actif_immobilisé',
        ),
        migrations.RemoveField(
            model_name='bilan',
            name='category',
        ),
        migrations.AddField(
            model_name='bilan',
            name='capitaux_propre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='créances',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='dette_de_financement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='dette_à_court_terme',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='trésorerie_actif',
            field=models.FloatField(default=0),
        ),
    ]
