# Generated by Django 4.2.1 on 2023-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bilan_capitaux_propre_alter_bilan_créances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='actif_immobilisé',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='capitaux_propre',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='créances',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='dette_de_financement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='dette_à_court_terme',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='trésorerie_actif',
            field=models.FloatField(default=0),
        ),
    ]
