# Generated by Django 4.2.1 on 2023-06-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_actif_bilan_actif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actif',
        ),
        migrations.RemoveField(
            model_name='bilan',
            name='actif',
        ),
    ]
