# Generated by Django 4.2.1 on 2023-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_delete_actif_remove_bilan_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='actif',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='autonomie_financiere',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='besoin_de_fond_roulement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='capacite_de_remboursement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='financement_permanent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='fond_de_roulement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='passif',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='solvabilite_general',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bilan',
            name='tresorie_net',
            field=models.FloatField(default=0),
        ),
    ]
