# Generated by Django 4.2.1 on 2023-06-19 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_tresorie_net_bilan_tresorerie_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
