# Generated by Django 4.2.1 on 2023-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_bilan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='autonomie_financiere_text',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AddField(
            model_name='bilan',
            name='capacite_de_remboursement_text',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AddField(
            model_name='bilan',
            name='financement_permanent_text',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AddField(
            model_name='bilan',
            name='solvabilite_general_text',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='actif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='actif_immobilisé',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='autonomie_financiere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='besoin_de_fond_roulement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='capacite_de_remboursement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='capitaux_propre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='créances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='dette_de_financement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='dette_à_court_terme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='financement_permanent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='fond_de_roulement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='passif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='solvabilite_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='tresorerie_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='trésorerie_actif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
