# Generated by Django 4.2.1 on 2023-06-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif_immobilisé', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('créances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trésorerie_actif', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capitaux_propre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dette_de_financement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dette_à_court_terme', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(max_length=266)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
